#! /bin/sh

# Display detection
if (xrandr -q | grep 'HDMI-1 connected'); then
	notify-send "Dual monitor detected"
	xrandr --output HDMI-1 --mode 1920x1080 --left-of eDP-1 --primary --output eDP-1 --mode 1920x1080
	bspc monitor eDP-1 -d IX X
	bspc monitor HDMI-1 -d I II III IV V VI VII VIII
else
	notify-send "Single monitor detected"
	bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
fi

# Launch everything
sxhkd &
~/.config/polybar/launch.sh --grayblocks &
picom -f &
nitrogen --restore &


bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Slack desktop='^1'
bspc rule -a Firefox desktop='^2'
bspc rule -a Code desktop='^5'
bspc rule -a obsidian desktop='^6'
bspc rule -a Google-chrome desktop='^9'
